### ISSUE TITLE
Inserting records with shared associations

### ISSUE THREAD

**Issue by axelson** [beam-community/ex_machina#285]
I'm trying to inserting a tree of objects.

```
community
  has_many topics
  has_many community_members
topic
  belongs_to community
  owned_by community_member
community_member
  belongs_to community
```

Right now I am working on the topic factory and I am trying to create a topic that is owned by a commnity_member that is part of the same community as the topic but I am unable to figure out how to do so.

My factory function currently looks like this:

```
      def topic_factory do
        %Communities.Topic{
          name: sequence(:name, &"Discussion Topic-#{&1}"),
          owner: build(:community_member),
          community: build(:community),
        }
      end
```

But the problem is that the owner of the topic ends up in a different community than the topic is in.

If I think change the factory function to:

```
      def topic_factory do
        community = build(:community)
        %Communities.Topic{
          name: sequence(:name, &"Discussion Topic-#{&1}"),
          owner: build(:community_member, community: community),
          community: community,
        }
      end
```

Then I get a primary key violation on the community since it is being inserted twice with the same id. Is there something I can do to mark both community "instances" as the same so that they will only be inserted once?

**Comment by aditya7iyengar** [comment]
@axelson I don't think this should give you an error. Could you share the exact error you're getting and the factory functions for `community` and `community_member`? 

Also, did you try something like this? 

```elixir
def topic_factory do
  community_member = build(:community_member)
  %Communities.Topic{
    name: sequence(:name, &"Discussion Topic-#{&1}"),
    owner: community_member,
    community: community_member.community
  }
end
```

**Comment by AndrewDryga** [comment]
Here is another example:

```
  def transport_factory do
    id = Ecto.UUID.generate()
    # TODO: This insert is weird, but ExMaching would do 2 inserts otherwise
    # and violate pkey contraint. How to deal with it?
    account = TalkInto.Domain.Factories.Account.insert(:account)
    page_id = sequence(:fb_page_id, &"PAGEID#{&1}")

    %Transport{
      id: id,
      title: sequence(:transport_title, &"Facebook Page #{&1}"),
      status: "active",
      provider: "facebook_messenger",
      provider_identifier: page_id,
      provider_settings: %{
        "page_id" => page_id,
        "page_access_token" => "fb_page_access_token"
      },
      account: account,
      events: [build(:transport_created_event, transport_id: id, account: account)],
      deleted_at: nil
    }
  end

  def transport_created_event_factory do
    %Transport.Event{
      action: "created",
      reason: nil,
      actor_type: "user",
      account: TalkInto.Domain.Factories.Account.build(:account),
      user: TalkInto.Domain.Factories.User.build(:user)
    }
  end
```

After we run `insert(:transport)` ExMachina would try to insert Account twice and violate the primary key constraint. The only feasible workaround is to use `account_id: account_id` instead of `account: account` in `Transport.Event` factory, but it looks messy - you need to keep in mind where you should use the struct and where just ID of it (you can not use both at the same time for obvious reasons).

**Comment by germsvel** [comment]
Hi @axelson and @AndrewDryga, when the associations reference each other in the factory definition, trying to `insert` them will lead to that primary key constraint violation, like you mention. 

That's normal because `ex_machina` is building the nested structs and then trying to insert them. A better explanation of this can be found in https://github.com/thoughtbot/ex_machina/issues/213#issuecomment-330258159

**Comment by germsvel** [comment]
@AndrewDryga we're not actually inserting the same record twice. We're building the whole struct (with all the nested structs), we cast all the values, and then we're using Ecto's [insert!/2](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert!/2) with the whole thing. 

I've played around with the alternate implementations where we remove the most deeply nested struct before inserting it, but it's a little bit strange. It can lead to some unexpected results, since we're just deleting data that the user of ex_machina explicitly wanted in there. I have also thought about the idea you mention: inserting the structs separately and then putting them back together. But at that point we are making multiple inserts, just like the user has to do right now, except that it would be more hidden from the user, and I think less clear. 

Still, I think the way it currently works is confusing to people because it is a bit unexpected so I'm still looking into ways that it could be improved.

**Comment by axelson** [comment]
If we pregenerate the primary key (relatively easy for me since I use UUID's), could we somehow take advantage of upserts? Although maybe we'd need a new function `MyApp.Factory.upsert` since the semantics might be different.

**Comment by axelson** [comment]
Just ran into this again today, was able to work around it slightly better with the new factory/1 definitions. It looks something like this:

```
def topic_factory(attrs) do
  # NOTE: Requires an inserted community to be passed in as an attribute
  community = Map.fetch!(attrs, :community)

  topic = %Communities.Topic{
    name: sequence(:name, &"Discussion Topic-#{&1}"),
    owner: build(:community_member, community: community),
    community: community,
  }

  merge_attributes(topic, attrs)
end
```

Although in the place where I used this today it was actually deeper in the association hierarchy so I had to remove the passed in attribute from the attrs map (otherwise the `merge_attributes` call would fail).
