### ISSUE TITLE
[Question] Load order of related data

### ISSUE THREAD

**Issue by zimt28** [beam-community/ex_machina#303]
Let‘s say I have a `Shop` context with a `list_customers/1` function (takes as shop as argument). Now I want to test it:

```elixir
shop = insert(:shop, customers: build_pair(:customer)

assert shop.customers == Shop.list_customers(shop)
```

The problem I have here is, that `insert` reverts the order of the customers I built using `build_pair` for some reason. 

Is there a way to tell ExMachine in which order to return the associated data? If not, it would be great if there was a way to tell ExMachina which fields it should explicitly load and in which order (this is related to https://github.com/thoughtbot/ex_machina/issues/295)

**Comment by germsvel** [comment]
Hi @zimt28 it's possible that `insert` is accidentally reverting the order of `build_pair`, though it seems strange that it would be doing that.

Could you confirm for me what `build_pair(:customer)` returns and what is it you're expecting out of `Shop.list_customers(shop)`? Does `list_customers/1` do any kind of sorting?

**Comment by Strayer** [comment]
I have a similar issue, though I'm not using build_pair but explicitly define multiple entries by hand:

```
%Project.Schema{
  objects: [build(:object) build(:object, amount: 100), build(:object, amount: 500)]
}
```

I'm testing a utility function that loads all Schema objects from Postgres with their objects – the objects are always returned in a reverse order by my utility function. At first I thought this might just be because the Query in the utility function doesn't specify a order_by for the relation_objects, but since this issue is having the same problem, maybe there is actually something going awkward here.
