### ISSUE TITLE
build/2 doesn't set parent id

### ISSUE THREAD

**Issue by speeddragon** [beam-community/ex_machina#336]
I'm using 2.3.0 of ex_machina, and I've notice that when I use `build/2` instead of `insert/2` and pass an item as argument, the argument_id is not filled when called with `build/2`.

**Example**

```
post = insert(:post)
build(:comment, post: post)
```

Current behaviour
```
%Comment{
  post: %Post{ ... },
  post_id: nil
}
```

Expected behaviour

```
%Comment{
  post: %Post{ ... },
  post_id: 1
}
```

It works if I put the id explicitly, like `build(:comment, post_id: post.id)`, but I think it might make sense to have this as a feature request maybe ?

**Comment by germsvel** [comment]
Hi @speeddragon, you're totally right that it doesn't set the foreign key when using `build/2`. 

`build/2` simply grabs the struct defined in the factory and merges any attributes you pass in. It doesn't have any notion that what you're passing in is an association. So since you're passing `post: insert(:post)`, it'll have the `post` but not the `post_id` set. 

If you were to have `post: build(:post)` defined in the factory, and you used an `insert(:comment)`, ecto would then set the association correctly. So that's why it works in that scenario. 

That being said, I agree that it's a little surprising, and what you're suggesting might be more expected. I'm not sure how we could best address this though. Do you have any thoughts?

**Comment by speeddragon** [comment]
I took a look into the source code, the insert is handle in here.

```elixir
def handle_insert(%{__meta__: %{__struct__: Ecto.Schema.Metadata}} = record, %{repo: repo}) do
    record
    |> cast
    |> repo.insert!
end
```

When record arrives doesn't have any id, when is inserted have all ids, so this logic that I wrote is handled by Ecto, the ex_machina only map that to the struct object right ?

We probably needed a way to check which column is the id, and append to the `table_` + (column id)` ? I know that this logic is defined in the the schema, probably not a easy solution to implement.

Went I have more time a can time a further look, but if you have any suggestion please let me know.
