### ISSUE TITLE
Use of `build( ... )` with Ecto 3.4+ leads to many association preload warnings

### ISSUE THREAD

**Issue by jeremy-hanna** [beam-community/ex_machina#393]
__Summary__
Relating to some changes in Ecto for this [bug](https://github.com/elixir-ecto/ecto/issues/3246), [a warning](https://github.com/elixir-ecto/ecto/commit/8c4135fb14f3ee57c06ce0c3984d9475d0a4a435) is emitted on the attempted Preload of associations that exist a built struct without a parent_id on the associations.

This is similar to this issue: https://github.com/thoughtbot/ex_machina/issues/336

In future versions of Ecto, it looks like this will change further and error.

__Steps to reproduce__
I set up a [simple project environment](https://github.com/jeremy-hanna/ecto-warnings) for this. You can see the simple test cases [here](https://github.com/jeremy-hanna/ecto-warnings/blob/master/test/my_app/post_test.exs)

Effectively:
(1) make a relation using ecto  
(2) make a factory for the records  
(3) `Factory.build(:post, %{comments: [build(:comment)]}) |> Repo.Preload(:comments)` will emit a warning as the comment (which was previously ignored pre-3.4) as it is not of type `#Ecto.Association.NotLoaded<association :comments is not loaded>`, now checks if there is a parent fk id on the associated record  

__Expectation__
I think I would still expect this to work, and possibly maintain a fake but consistent parent fk id between these associated records

**Comment by robacarp** [comment]
I have a sneaking feeling this isn't going to scale well, but here's how I'm dealing with this problem. Perhaps this can be better represented in ExMachina.Ecto but perhaps there are a myriad of other concerns to doing it this way which I'm ignorant of:

- the factory itself renders an empty array onto the association field
- `with_` helpers merge in a built list which overwrites the association

Some psuedocode to show what I mean:

```elixir
def post_factory do
  %Post{
    comments: []
  }
end

def with_comments(post = %Post{}, count \\ 2) do
  %{post | comments: build_list(count, :comment)}
end
```

```elixir
test "post has comments" do
  build(:post) |> with_comments(2)
end
```

**Comment by robacarp** [comment]
Sure, yeah. I think it makes sense for ExMachina.Ecto.build to overlay (and perhaps call back to) ExMachina.build. That would give devs the ability to choose the older if they're so inclined. 

It could be a frustrating breaking change to roll out though, because presumably everyone has already written `import ExMachina.Ecto` into their apps and suddenly this would change the behavior of every build method being used. If it's the right solution it's probably worth biting off, but it'll cause some headaches I'm sure.

Whether or not that's the least surprising behavior remains to be evaluated. I ran into this when writing a View test, so I'm expecting my structs to be all preloaded up already. Maybe the right solution is to recommend calling Repo.preload in the with_comments/1 decorator above -- maybe that's what I'd want later when I'm testing a controller instead?

**Comment by baldwindavid** [comment]
@germsvel I rather like that `build` doesn't know or care about Ecto. However, one thing I have missed in ExMachina that ruby's FactoryBot (and Thoughtbot's) has is something similar to `build_stubbed` to produce a graph of records that "seem" like they are persisted. That can be very helpful in cutting down on the need to hit the database. Perhaps rather than changing `build`, a `build_stubbed` function is introduced that is fully aware of Ecto.

**Comment by baldwindavid** [comment]
Here is a very limited and opinionated build_stubbed strategy I've been using...
https://gist.github.com/baldwindavid/780449125ac4e9d064662895a0d65703

It does the following:
- Adds `inserted_at` and `updated_at` timestamps to all records in the tree if there is not already one
- Adds an `id` (specifically a UUID) to all records in the tree if there is not already one
- For belongs_to associations only: sets the foreign key of the child record to the associated parent ID

It doesn't handle syncing up IDs for any other associations. I just haven't needed it.

Example usage for the following `account` factory...

```elixir
def account_factory do
  %Account{
    property: build(:property)
  }
end
```

```elixir
account = build_stubbed(:account)
```

The account should have both the `property` and `property_id` set for the built property.

Example with an explicitly passed in property...

```elixir
property = build_stubbed(:property)
account = build_stubbed(:account, property: property)
```

The account should have both the `property` and `property_id` set and it should correspond with the `property` and `property_id` passed in. It should not override the property's already set `id`, `inserted_at`, and `updated_at`.
